//ISCSI
export const FETCH_ISCSI_START = "FETCH_ISCSI_START";
export const FETCH_ISCSI_SUCCESS = "FETCH_ISCSI_SUCCESS";
export const FETCH_ISCSI_FAIL = "FETCH_ISCSI_FAIL";

//SET
export const SET_ISCSI_START = "SET_ISCSI_START";
export const SET_ISCSI_SUCCESS = "SET_ISCSI_SUCCESS";
export const SET_ISCSI_FAIL = "SET_ISCSI_FAIL";
