//fetch hardware disk
export const FETCH_HARDWARE_DISK_START = "FETCH_HARDWARE_DISK_START";
export const FETCH_HARDWARE_DISK_SUCCESS = "FETCH_HARDWARE_DISK_SUCCESS";
export const FETCH_HARDWARE_DISK_FAIL = "FETCH_HARDWARE_DISK_FAIL";

//fetch hardware power
export const FETCH_HARDWARE_POWER_START = "FETCH_HARDWARE_POWER_START";
export const FETCH_HARDWARE_POWER_SUCCESS = "FETCH_HARDWARE_POWER_SUCCESS";
export const FETCH_HARDWARE_POWER_FAIL = "FETCH_HARDWARE_POWER_FAIL";

//fetch hardware eth
export const FETCH_HARDWARE_ETH_START = "FETCH_HARDWARE_ETH_START";
export const FETCH_HARDWARE_ETH_SUCCESS = "FETCH_HARDWARE_ETH_SUCCESS";
export const FETCH_HARDWARE_ETH_FAIL = "FETCH_HARDWARE_ETH_FAIL";

//fetch hardware iscsi
export const FETCH_HARDWARE_ISCSI_START = "FETCH_HARDWARE_ISCSI_START";
export const FETCH_HARDWARE_ISCSI_SUCCESS = "FETCH_HARDWARE_ISCSI_SUCCESS";
export const FETCH_HARDWARE_ISCSI_FAIL = "FETCH_HARDWARE_ISCSI_FAIL";

//fetch hardware fc
export const FETCH_HARDWARE_FC_START = "FETCH_HARDWARE_FC_START";
export const FETCH_HARDWARE_FC_SUCCESS = "FETCH_HARDWARE_FC_SUCCESS";
export const FETCH_HARDWARE_FC_FAIL = "FETCH_HARDWARE_FC_FAIL";

//blink disk
export const BLINK_DISK_START = "BLINK_DISK_START";
export const BLINK_DISK_SUCCESS = "BLINK_DISK_SUCCESS";
export const BLINK_DISK_FAIL = "BLINK_DISK_FAIL";
