//SMTP ACCOUNT
export const FETCH_ACCOUNT_START = "FETCH_ACCOUNT_START";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FAIL = "FETCH_ACCOUNT_FAIL";

//SMTP ACCOUNT UPDATE
export const UPDATE_ACCOUNT_START = "UPDATE_ACCOUNT_START";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_FAIL = "UPDATE_ACCOUNT_FAIL";

//SMTP ACCOUNT EXPORT
export const EXPORT_ACCOUNT_START = "EXPORT_ACCOUNT_START";
export const EXPORT_ACCOUNT_SUCCESS = "EXPORT_ACCOUNT_SUCCESS";
export const EXPORT_ACCOUNT_FAIL = "EXPORT_ACCOUNT_FAIL";

//SMTP ACCOUNT VERIFY
export const VERIFY_ACCOUNT_START = "VERIFY_ACCOUNT_START";
export const VERIFY_ACCOUNT_SUCCESS = "VERIFY_ACCOUNT_SUCCESS";
export const VERIFY_ACCOUNT_FAIL = "VERIFY_ACCOUNT_FAIL";

//SMTP ACCOUNT IMPORT
export const IMPORT_ACCOUNT_START = "IMPORT_ACCOUNT_START";
export const IMPORT_ACCOUNT_SUCCESS = "IMPORT_ACCOUNT_SUCCESS";
export const IMPORT_ACCOUNT_FAIL = "IMPORT_ACCOUNT_FAIL";
