//events fetch
export const FETCH_EVENTS_START = "FETCH_EVENTS_START";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAIL = "FETCH_EVENTS_FAIL";

//events export
export const EXPORT_EVENTS_START = "EXPORT_EVENTS_START";
export const EXPORT_EVENTS_SUCCESS = "EXPORT_EVENTS_SUCCESS";
export const EXPORT_EVENTS_FAIL = "EXPORT_EVENTS_FAIL";

//events clear
export const CLEAR_EVENTS_START = "CLEAR_EVENTS_START";
export const CLEAR_EVENTS_SUCCESS = "CLEAR_EVENTS_SUCCESS";
export const CLEAR_EVENTS_FAIL = "CLEAR_EVENTS_FAIL";
