//SMTP RECIPIENT
export const FETCH_RECIPIENT_START = "FETCH_RECIPIENT_START";
export const FETCH_RECIPIENT_SUCCESS = "FETCH_RECIPIENT_SUCCESS";
export const FETCH_RECIPIENT_FAIL = "FETCH_RECIPIENT_FAIL";

//SMTP RECIPIENT IMPORT
export const IMPORT_RECIPIENT_START = "IMPORT_RECIPIENT_START";
export const IMPORT_RECIPIENT_SUCCESS = "IMPORT_RECIPIENT_SUCCESS";
export const IMPORT_RECIPIENT_FAIL = "IMPORT_RECIPIENT_FAIL";

//SMTP RECIPIENT CREATE
export const CREATE_RECIPIENT_START = "CREATE_RECIPIENT_START";
export const CREATE_RECIPIENT_SUCCESS = "CREATE_RECIPIENT_SUCCESS";
export const CREATE_RECIPIENT_FAIL = "CREATE_RECIPIENT_FAIL";

//SMTP RECIPIENT DELETE
export const DELETE_RECIPIENT_START = "DELETE_RECIPIENT_START";
export const DELETE_RECIPIENT_SUCCESS = "DELETE_RECIPIENT_SUCCESS";
export const DELETE_RECIPIENT_FAIL = "DELETE_RECIPIENT_FAIL";

//SMTP RECIPIENT EDIT
export const EDIT_RECIPIENT_START = "EDIT_RECIPIENT_START";
export const EDIT_RECIPIENT_SUCCESS = "EDIT_RECIPIENT_SUCCESS";
export const EDIT_RECIPIENT_FAIL = "EDIT_RECIPIENT_FAIL";
