//update system
export const UPDATE_SYSTEM_START = "UPDATE_SYSTEM_START";
export const UPDATE_SYSTEM_SUCCESS = "UPDATE_SYSTEM_SUCCESS";
export const UPDATE_SYSTEM_FAIL = "UPDATE_SYSTEM_FAIL";

//export system log
export const EXPORT_LOG_START = "EXPORT_LOG_START";
export const EXPORT_LOG_SUCCESS = "EXPORT_LOG_SUCCESS";
export const EXPORT_LOG_FAIL = "EXPORT_LOG_FAIL";

//check system status
export const CHECK_STATUS_START = "CHECK_STATUS_START";
export const CHECK_STATUS_SUCCESS = "CHECK_STATUS_SUCCESS";
export const CHECK_STATUS_FAIL = "CHECK_STATUS_FAIL";

//reboot system
export const REBOOT_SYSTEM_START = "REBOOT_SYSTEM_START";
export const REBOOT_SYSTEM_SUCCESS = "REBOOT_SYSTEM_SUCCESS";
export const REBOOT_SYSTEM_FAIL = "REBOOT_SYSTEM_FAIL";

//shutdown system
export const SHUTDOWN_SYSTEM_START = "SHUTDOWN_SYSTEM_START";
export const SHUTDOWN_SYSTEM_SUCCESS = "SHUTDOWN_SYSTEM_SUCCESS";
export const SHUTDOWN_SYSTEM_FAIL = "SHUTDOWN_SYSTEM_FAIL";
