//EXPORT

//performance export DISK
export const EXPORT_PERFORMANCE_DISK_START = "EXPORT_PERFORMANCE_DISK_START";
export const EXPORT_PERFORMANCE_DISK_SUCCESS = "EXPORT_PERFORMANCE_DISK_SUCCESS";
export const EXPORT_PERFORMANCE_DISK_FAIL = "EXPORT_PERFORMANCE_DISK_FAIL";

//performance export STORAGE
export const EXPORT_PERFORMANCE_STORAGE_START = "EXPORT_PERFORMANCE_STORAGE_START";
export const EXPORT_PERFORMANCE_STORAGE_SUCCESS = "EXPORT_PERFORMANCE_STORAGE_SUCCESS";
export const EXPORT_PERFORMANCE_STORAGE_FAIL = "EXPORT_PERFORMANCE_STORAGE_FAIL";

//performance export ISCSI
export const EXPORT_PERFORMANCE_ISCSI_START = "EXPORT_PERFORMANCE_ISCSI_START";
export const EXPORT_PERFORMANCE_ISCSI_SUCCESS = "EXPORT_PERFORMANCE_ISCSI_SUCCESS";
export const EXPORT_PERFORMANCE_ISCSI_FAIL = "EXPORT_PERFORMANCE_ISCSI_FAIL";

//performance export FC
export const EXPORT_PERFORMANCE_FC_START = "EXPORT_PERFORMANCE_FC_START";
export const EXPORT_PERFORMANCE_FC_SUCCESS = "EXPORT_PERFORMANCE_FC_SUCCESS";
export const EXPORT_PERFORMANCE_FC_FAIL = "EXPORT_PERFORMANCE_FC_FAIL";

//REPORT

//performance report DISK
export const REPORT_PERFORMANCE_DISK_START = "REPORT_PERFORMANCE_DISK_START";
export const REPORT_PERFORMANCE_DISK_SUCCESS = "REPORT_PERFORMANCE_DISK_SUCCESS";
export const REPORT_PERFORMANCE_DISK_FAIL = "REPORT_PERFORMANCE_DISK_FAIL";

//performance report STORAGE
export const REPORT_PERFORMANCE_STORAGE_START = "REPORT_PERFORMANCE_STORAGE_START";
export const REPORT_PERFORMANCE_STORAGE_SUCCESS = "REPORT_PERFORMANCE_STORAGE_SUCCESS";
export const REPORT_PERFORMANCE_STORAGE_FAIL = "REPORT_PERFORMANCE_STORAGE_FAIL";

//performance report ISCSI
export const REPORT_PERFORMANCE_ISCSI_START = "REPORT_PERFORMANCE_ISCSI_START";
export const REPORT_PERFORMANCE_ISCSI_SUCCESS = "REPORT_PERFORMANCE_ISCSI_SUCCESS";
export const REPORT_PERFORMANCE_ISCSI_FAIL = "REPORT_PERFORMANCE_ISCSI_FAIL";

//performance report FC
export const REPORT_PERFORMANCE_FC_START = "REPORT_PERFORMANCE_FC_START";
export const REPORT_PERFORMANCE_FC_SUCCESS = "REPORT_PERFORMANCE_FC_SUCCESS";
export const REPORT_PERFORMANCE_FC_FAIL = "REPORT_PERFORMANCE_FC_FAIL";
