//snap shot
export const FETCH_SNAPSHOT_START = "FETCH_SNAPSHOT_START";
export const FETCH_SNAPSHOT_SUCCESS = "FETCH_SNAPSHOT_SUCCESS";
export const FETCH_SNAPSHOT_FAIL = "FETCH_SNAPSHOT_FAIL";

//create snap shot
export const CREATE_SNAPSHOT_START = "CREATE_SNAPSHOT_START";
export const CREATE_SNAPSHOT_SUCCESS = "CREATE_SNAPSHOT_SUCCESS";
export const CREATE_SNAPSHOT_FAIL = "CREATE_SNAPSHOT_FAIL";

//extend snap shot
export const EXTEND_SNAPSHOT_START = "EXTEND_SNAPSHOT_START";
export const EXTEND_SNAPSHOT_SUCCESS = "EXTEND_SNAPSHOT_SUCCESS";
export const EXTEND_SNAPSHOT_FAIL = "EXTEND_SNAPSHOT_FAIL";

//delete snap shot
export const DELETE_SNAPSHOT_START = "DELETE_SNAPSHOT_START";
export const DELETE_SNAPSHOT_SUCCESS = "DELETE_SNAPSHOT_SUCCESS";
export const DELETE_SNAPSHOT_FAIL = "DELETE_SNAPSHOT_FAIL";

//restoer snap shot
export const RESTORE_SNAPSHOT_START = "RESTORE_SNAPSHOT_START";
export const RESTORE_SNAPSHOT_SUCCESS = "RESTORE_SNAPSHOT_SUCCESS";
export const RESTORE_SNAPSHOT_FAIL = "RESTORE_SNAPSHOT_FAIL";
