//fetch role
export const FETCH_ROLE_START = "FETCH_ROLE_START";
export const FETCH_ROLE_SUCCESS = "FETCH_ROLE_SUCCESS";
export const FETCH_ROLE_FAIL = "FETCH_ROLE_FAIL";

//create role
export const CREATE_ROLE_START = "CREATE_ROLE_START";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";

//delete role
export const DELETE_ROLE_START = "DELETE_ROLE_START";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";

//fetch entities
export const FETCH_ENTITIES_START = 'FETCH_ENTITIES_START'
export const FETCH_ENTITIES_SUCCESS = 'FETCH_ENTITIES_SUCCESS'
export const FETCH_ENTITIES_FAIL = 'FETCH_ENTITIES_FAIL'
