//initiator
export const INIT_FETCH_INITIATORS = "INIT_FETCH_INITIATORS";
export const FETCH_INITIATOR_START = "FETCH_INITIATOR_START";
export const FETCH_INITIATOR_SUCCESS = "FETCH_INITIATOR_SUCCESS";
export const FETCH_INITIATOR_FAIL = "FETCH_INITIATOR_FAIL";

//add to host initiator
export const ADD_TO_HOST_START = "ADD_TO_HOST_START";
export const ADD_TO_HOST_SUCCESS = "ADD_TO_HOST_SUCCESS";
export const ADD_TO_HOST_FAIL = "ADD_TO_HOST_FAIL";
