//pools
export const FETCH_POOLS_START = "FETCH_POOLS_START";
export const FETCH_POOLS_SUCCESS = "FETCH_POOLS_SUCCESS";
export const FETCH_POOLS_FAIL = "FETCH_POOLS_FAIL";

//delete pool
export const DELETE_POOLS_START = "DELETE_POOLS_START";
export const DELETE_POOLS_SUCCESS = "DELETE_POOLS_SUCCESS";
export const DELETE_POOLS_FAIL = "DELETE_POOLS_FAIL";

//create pool
export const CREATE_POOL_START = "CREATE_POOL_START";
export const CREATE_POOL_SUCCESS = "CREATE_POOL_SUCCESS";
export const CREATE_POOL_FAIL = "CREATE_POOL_FAIL";

//rename pool
export const RENAME_POOL_START = "RENAME_POOL_START";
export const RENAME_POOL_SUCCESS = "RANAME_POOL_SUCCESS";
export const RENAME_POOL_FAIL = "RENAME_POOL_FAIL" ; 
    
//extend pool
export const EXTEND_POOLS_START = "EXTEND_POOLS_START";
export const EXTEND_POOLS_SUCCESS = "EXTEND_POOLS_SUCCESS";
export const EXTEND_POOLS_FAIL = "EXTEND_POOLS_FAIL";
    
