//rapidstore
export const FETCH_RAPIDSTORE_START = "FETCH_RAPIDSTORE_START";
export const FETCH_RAPIDSTORE_SUCCESS = "FETCH_RAPIDSTORE_SUCCESS";
export const FETCH_RAPIDSTORE_FAIL = "FETCH_RAPIDSTORE_FAIL";

//delete rapidstore
export const DELETE_RAPIDSTORE_START = "DELETE_RAPIDSTORE_START";
export const DELETE_RAPIDSTORE_SUCCESS = "DELETE_RAPIDSTORE_SUCCESS";
export const DELETE_RAPIDSTORE_FAIL = "DELETE_RAPIDSTORE_FAIL";

//create rapidstore
export const CREATE_RAPIDSTORE_START = "CREATE_RAPIDSTORE_START";
export const CREATE_RAPIDSTORE_SUCCESS = "CREATE_RAPIDSTORE_SUCCESS";
export const CREATE_RAPIDSTORE_FAIL = "CREATE_RAPIDSTORE_FAIL";

//fetch rapidstore status
export const FETCH_RAPIDSTORE_STATUS_START = "FETCH_RAPIDSTORE_STATUS_START";
export const FETCH_RAPIDSTORE_STATUS_SUCCESS ="FETCH_RAPIDSTORE_STATUS_SUCCESS";
export const FETCH_RAPIDSTORE_STATUS_FAIL = "FETCH_RAPIDSTORE_STATUS_FAIL";
