//network
export const FETCH_NETWORK_START = "FETCH_NETWORK_START";
export const FETCH_NETWORK_SUCCESS = "FETCH_NETWORK_SUCCESS";
export const FETCH_NETWORK_FAIL = "FETCH_NETWORK_FAIL";

//set network
export const SET_NETWORK_START = "SET_NETWORK_START";
export const SET_NETWORK_SUCCESS = "SET_NETWORK_SUCCESS";
export const SET_NETWORK_FAIL = "SET_NETWORK_FAIL";
